# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    # Not Working, but standalone WinADController is working so it should work
    ldap:
        class: Symfony\Component\Ldap\Ldap
        arguments: ['@ext_ldap_adapter']
    ext_ldap_adapter:
        class: Symfony\Component\Ldap\Adapter\ExtLdap\Adapter
        arguments:
            -   host: "internal.imsglobal.com"
    AppBundle\Service\FileUploader:
        class: AppBundle\Service\FileUploader
        arguments:
            $targetDir: 'C:\ProgramData\MySQL\MySQL Server 5.7\Data\pharmareport_config'
    GsrmImportMapping:
        class: AppBundle\Services\GsrmImportMapping
    GsrmExportMapping:
        class: AppBundle\Services\GsrmExportMapping
