# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                    qlik_srv:
                        password: 12azQSwx
                        roles: [ROLE_ADMIN,ROLE_USER]
                    forcea\qlik_srv:
                        password: 12azQSwx
                        roles: [ROLE_ADMIN,ROLE_USER]
      # Not Working, but standalone WinADController is working so it should work
      #  ldap_provider:
      #      ldap:
      #          service: ldap
      #          base_dn: dc=example,dc=com
      #          search_dn: "cn=read-only-admin,dc=example,dc=com"
      #          search_password: password
      #          default_roles: ROLE_USER
      #          uid_key: uid

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
          # form_login_ldap:
            form_login:
              login_path: login
              check_path: login
          #    service: ldap
          #    dn_string: 'uid={username},dc=example,dc=com'

            # logout
            logout:
                path:   /logout
                target: /login
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
