<?php

namespace AppBundle\Repository;

/**
 * DwhCustomHierarchiesForTargetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwhCustomHierarchiesForTargetsRepository extends \Doctrine\ORM\EntityRepository
{
}
