<?php

namespace AppBundle\Repository;

/**
 * DwhCustomHierarchiesForTargetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DwhCustomHierarchiesForTargetsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDistinctValues($columns, $clientoutputid)
    {
        $alias = 'd';
        $qb = $this->createQueryBuilder($alias);

        foreach ($columns as &$columnName) {
            $columnName = $alias . '.' . $columnName;
        }

        $qb
          ->select($columns)
          ->where($alias . '.clientOutputId = :id')
          ->setParameter('id', $clientoutputid)
          ->distinct()
        ;

        return $qb
          ->getQuery()
          ->getArrayResult()
        ;
    }

}
