<?php

namespace AppBundle\Repository;

/**
 * GsrmDataQualityChecksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GsrmDataQualityChecksRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistinctClientOutputId($loadDate)
    {
        $qb = $this->createQueryBuilder('d');

        $qb
          ->select('d.clientOutputId')
          ->where('d.loadDate = :loadDateParameter')
          ->setParameter('loadDateParameter', $loadDate)
          ->distinct()
        ;

        return $qb
          ->getQuery()
          ->getArrayResult()
        ;
    }

    public function getWarningsForOneClientoutputId($loadDate, $clientoutputId)
    {
        $qb = $this->createQueryBuilder('d');

        $qb
          ->select('d.status')
          ->where('d.loadDate = :loadDateParam')
          ->setParameter('loadDateParam', $loadDate)
          ->andwhere('d.clientOutputId = :clientoutputIdParam')
          ->setParameter('clientoutputIdParam', $clientoutputId)
          ->andWhere('d.status = :statusParam')
          ->setParameter('statusParam', 'WARNING')
        ;

        return $qb
          ->getQuery()
          ->getArrayResult()
        ;
    }
}
